# Generated by Django 2.2.16 on 2020-11-22 02:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

  dependencies = [
    ("bella", "0001_create_garment"),
  ]

  operations = [
    migrations.CreateModel(
      name="Picture",
      fields=[
        (
          "id",
          models.AutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
          ),
        ),
        ("file", models.FileField(upload_to="")),
      ],
    ),
  ]
