# Generated by Django 2.2.16 on 2020-11-22 02:19
from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ("bella", "0002_create_picture"),
  ]

  operations = [
    migrations.DeleteModel(name="Picture",),
  ]
