# Generated by Django 2.2.16 on 2020-11-22 02:22
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

  dependencies = [
    ("bella", "0003_drop_picture"),
  ]

  operations = [
    migrations.CreateModel(
      name="GarmentPicture",
      fields=[
        (
          "id",
          models.AutoField(
            auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
          ),
        ),
        ("file", models.FileField(upload_to="")),
        (
          "garment",
          models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bella.Garment"),
        ),
      ],
    ),
  ]
