# Generated by Django 2.2.16 on 2020-11-22 17:55
import bella.app.models
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

  dependencies = [
    ("bella", "0004_create_garmentpicture"),
  ]

  operations = [
    migrations.AlterField(
      model_name="garmentpicture",
      name="file",
      field=models.FileField(upload_to=bella.app.models.generate_upload_path),
    ),
    migrations.AlterField(
      model_name="garmentpicture",
      name="garment",
      field=models.ForeignKey(
        on_delete=django.db.models.deletion.CASCADE, related_name="picture_set", to="bella.Garment",
      ),
    ),
  ]
