# Generated by Django 3.2 on 2020-11-22 23:18
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

  dependencies = [
    ("bella", "0005_fix_garmentpicture"),
  ]

  operations = [
    migrations.AlterField(
      model_name="garmentpicture",
      name="garment",
      field=models.ForeignKey(
        on_delete=django.db.models.deletion.CASCADE, related_name="pictures", to="bella.garment"
      ),
    ),
  ]
