# Generated by Django 3.2 on 2020-11-22 23:19
import bella.app.models
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

  dependencies = [
    ("bella", "0006_update_garmentpicture_related_name"),
  ]

  operations = [
    migrations.CreateModel(
      name="Outfit",
      fields=[
        (
          "id",
          models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        ("name", models.CharField(max_length=200)),
      ],
    ),
    migrations.CreateModel(
      name="OutfitPicture",
      fields=[
        (
          "id",
          models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        ("file", models.FileField(upload_to=bella.app.models.generate_upload_path)),
        (
          "outfit",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name="outfits", to="bella.outfit"
          ),
        ),
      ],
    ),
  ]
