# Generated by Django 3.2 on 2020-11-22 23:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

  dependencies = [
    ("bella", "0007_create_outfit"),
  ]

  operations = [
    migrations.AddField(
      model_name="outfit",
      name="garments",
      field=models.ManyToManyField(related_name="outfits", to="bella.Garment"),
    ),
  ]
