# Generated by Django 3.2 on 2020-11-22 23:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

  dependencies = [
    ("bella", "0008_create_outfit_garment_relation"),
  ]

  operations = [
    migrations.AlterField(
      model_name="outfit",
      name="garments",
      field=models.ManyToManyField(blank=True, related_name="outfits", to="bella.Garment"),
    ),
  ]
