# Generated by Django 3.2 on 2020-11-23 01:25
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

  dependencies = [
    ("bella", "0010_alter_outfitpicture_related_name"),
  ]

  operations = [
    migrations.CreateModel(
      name="Shop",
      fields=[
        (
          "id",
          models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        ("name", models.CharField(max_length=100)),
        ("url", models.URLField(blank=True, max_length=1000)),
      ],
    ),
    migrations.CreateModel(
      name="Product",
      fields=[
        (
          "id",
          models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        ("name", models.CharField(max_length=100)),
        ("url", models.URLField(blank=True, max_length=1000)),
        (
          "garment",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name="products",
            to="bella.garment",
          ),
        ),
        (
          "shop",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name="products", to="bella.shop"
          ),
        ),
      ],
    ),
  ]
